import fs from "node:fs/promises";
const sources=JSON.parse(await fs.readFile(new URL("../data/sources.json",import.meta.url),"utf8"));
if(!process.env.OPENAI_API_KEY) throw new Error("OPENAI_API_KEY manquante");
const domains=sources.map(s=>s.domain);
const schema={type:"object",additionalProperties:false,properties:{week:{type:"string"},items:{type:"array",minItems:5,maxItems:6,items:{type:"object",additionalProperties:false,properties:{category:{type:"string"},title:{type:"string"},source:{type:"string"},source_url:{type:"string"},publication_date:{type:"string"},summary:{type:"string"},facts:{type:"string"},legal_question:{type:"string"},solution:{type:"string"},practical_relevance:{type:"string"},confidence:{type:"number"}},required:["category","title","source","source_url","publication_date","summary","facts","legal_question","solution","practical_relevance","confidence"]}}},required:["week","items"]};
const input=["Prépare en français la veille IP des 7 derniers jours.","Recherche obligatoirement sur le web et uniquement dans les domaines autorisés.","Sélectionne 5 ou 6 contenus vérifiables et diversifiés: marques, brevets, dessins et modèles, droit d'auteur et un sujet connexe.","Privilégie les décisions, textes et annonces des sources primaires.","Ne complète jamais une référence absente. Chaque URL doit mener directement à la source utilisée.","Pour chaque item, explique faits, question juridique, solution et portée pratique.","Domaines autorisés: "+domains.join(", ")].join("\n");
const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({model:process.env.OPENAI_MODEL||"gpt-5.6-terra",reasoning:{effort:"high"},tools:[{type:"web_search",filters:{allowed_domains:domains},external_web_access:true}],tool_choice:"required",input,text:{format:{type:"json_schema",name:"veille_ip",strict:true,schema}}})});
const raw=await response.json();
if(!response.ok) throw new Error(JSON.stringify(raw));
const output=raw.output?.flatMap(o=>o.content||[]).find(c=>c.type==="output_text")?.text;
if(!output) throw new Error("Sortie structurée absente");
const report=JSON.parse(output);
report.generated_at=new Date().toISOString();
report.status="generated";
await fs.mkdir("public/reports",{recursive:true});
await fs.writeFile("public/latest.json",JSON.stringify(report,null,2)+"\n");
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const body=report.items.map(x=>`<article><small>${esc(x.category)} · ${esc(x.source)} · ${esc(x.publication_date)}</small><h2>${esc(x.title)}</h2><h3>Faits</h3><p>${esc(x.facts)}</p><h3>Question de droit</h3><p>${esc(x.legal_question)}</p><h3>Solution</h3><p>${esc(x.solution)}</p><h3>Portée pratique</h3><p>${esc(x.practical_relevance)}</p><p><a href="${esc(x.source_url)}">Voir la source primaire</a></p></article>`).join("");
const html=`<!doctype html><html lang="fr"><head><meta charset="utf-8"><title>Veille IP - ${esc(report.week)}</title><style>body{font:15px/1.6 Arial;max-width:820px;margin:55px auto;padding:0 25px;color:#17211d}h1{text-align:center;font-family:Georgia}article{margin:42px 0;break-inside:avoid}h2{color:#173b31}h3{font-size:14px;margin-bottom:0}small{color:#68736e}a{color:#173b31}@media print{body{margin:0}}</style></head><body><h1>Veille Propriété intellectuelle</h1><p style="text-align:center">Semaine du ${esc(report.week)}</p>${body}</body></html>`;
const slug=new Date().toISOString().slice(0,10);
await fs.writeFile(`public/reports/veille-${slug}.html`,html);
console.log(`Generated ${report.items.length} items for ${report.week}`);